### ISSUE TITLE
updating zend-hydrator to 2.0 via composer oddity

### ISSUE THREAD

**Issue by shaunfreeman** [zendframework/zend-hydrator#18]
Hi
I have come across a strangeness I can't explain and think is a bug. When updating zend-hydrator via composer to version 2 it reverts other Zend modules to earlier incompatible versions the output is:

    Updating dependencies (including require-dev)
    - Removing zendframework/zend-stdlib (2.7.4)
    - Installing zendframework/zend-stdlib (2.6.0)
    Loading from cache
    
    - Removing zendframework/zend-hydrator (1.0.0)
    - Installing zendframework/zend-hydrator (2.0.0)
    Loading from cache
    
    - Removing zendframework/zend-modulemanager (2.6.1)
    - Installing zendframework/zend-modulemanager (2.5.3)
    Loading from cache
    
    - Removing zendframework/zend-form (2.6.0)
    - Installing zendframework/zend-form (2.5.3)
    Loading from cache
    
    - Removing zendframework/zend-mvc (2.6.0)
    - Installing zendframework/zend-mvc (2.5.3)
    Loading from cache
    
    - Removing zendframework/zend-db (2.6.2)
    - Installing zendframework/zend-db (2.5.2)
    Loading from cache

And when I change the zend-hyrator back to `'1.*'` it all goes back to the lastest `'2.*'` Zend modules
I am sure this can't be right, has anyone got any insights into this or am I the only one experiencing this?

Thanks inadvance

**Comment by svycka** [comment]
zend-hydrator v2.0 requires `"zendframework/zend-stdlib": "^2.5.1"` so it allows all above, but `zendframework/zend-stdlib` in version 2.7 was added `zend-hydrator:^1.0` so it cannot be used and then it falls back to 2.6 where `zend-hydrator` didn't existed so it allows it.

I think that's why, but not sure how to fix it. 

you could add `zend-hydrator:2.1` with has `"zendframework/zend-stdlib": "^3.0"` if you really want it, but you will have to fix other dependencies also.

**Comment by weierophinney** [comment]
We've since changed things in 1.1 and 2.1; 2.1 requires zend-stdlib ^3.0, while 1.1 requires zend-stdlib ^2.7. Essentially, you can only update to zend-hydrator v2 *if you can update to zend-stdlib v3*. This is on purpose.

When separating the hydrator subcomponent out of zend-stdlib, we had to make the situation backwards compatible for existing users. As such, zend-stdlib (in the v2 series) *still contains hydrator classes*. We updated them to remove implementation and extend those from zend-hydrator. This posed a bit of a problem, however: several classes in zend-stdlib's hydrators were marked final, which meant that in zend-hydrator, they could not be marked final if we wanted the classes in zend-stdlib to extend from them.

(We marked the classes final because they had internal details that should not be overridden. By marking them final, we force end-users to create their own implementations if they really, really need different behavior, saving us the maintentance cost of extension points.)

The sole reason for v2.0.0 was to be able to re-mark those classes as final — and that has the side effect of making it incompatible with v2 versions of zend-stdlib *if you are using the hydrators from zend-stdlib*.

zend-stdlib v3 removes the hydrator subcomponent completely, making it compatible with zend-hydrator v2 again. As such, we marked zend-hydrator v2.1 as depending on zend-stdlib v3.

We're just about done with migration of the various components to make them forwards compatible with zend-stdlib v3, among others. Once that happens, you should be able to update.

**Comment by shaunfreeman** [comment]
Thanks for that detailed explaination. I will be staying on v1 for now. Thanks for your help and work with zend framework.
