### ISSUE TITLE
is and has are not extracted like get in ClassMethods hydrator

### ISSUE THREAD

**Issue by skors** [zendframework/zend-hydrator#49]
Hello,

when extracting value from an object with the ClassMethods hydrator, the extracted array returns array keys which are not compatible as the array keys which are used for hydrating.

Is this so expected and i'm just expecting another behavior falsely?

Example:

```php
// my object

class MyClass 
{
    protected $active = true;

    public function isActive() : bool
    {
        return $this->active;
    }

    public function setActive(bool $active)
    {
        $this->active = $active;
    }
}

$hydrator = new \Zend\Hydrator\ClassMethods();

var_dump($hydrator->extract(new MyClass())); // returns ['is_active' => true]

// returns class Myclass#12 { protected $active => bool(true) }, expected  { protected $active => bool(false) }
var_dump($hydrator->hydrate(['is_active' => false], new MyClass())); 

// returns class Myclass#12 { protected $active => bool(false) }  as expected
var_dump($hydrator->hydrate(['active' => false], new MyClass()));
```

Shouldn't extraction remove the is like it does for get on extraction (see line 159ff in [ClassMethods.php](https://github.com/zendframework/zend-hydrator/blob/master/src/ClassMethods.php#L159))?

thanks in advance

**Comment by froschdesign** [comment]
@skors 
Sorry for the late response.

This result is correct:

> ```php
> // returns class Myclass#12 { protected $active => bool(true) }, expected  { protected $active => bool(false) }
> var_dump($hydrator->hydrate(['is_active' => false], new MyClass())); 
> ```

Because there is no setter with name like `setIsActive`.

This result is correct:

> ```php
> var_dump($hydrator->extract(new MyClass())); // returns ['is_active' => true]`
> ```

Please keep in mind, that the hydrator uses some filters for the methods to extract the data. The `ClassMethods` hydrator uses the `Zend\Hydrator\Filter\IsFilter`.

If you do not want the `is_active` on extraction, then remove the filter from the hydrator:

```php
$hydrator->getFilter()->removeFilter('is');
```

**Comment by skors** [comment]
@froschdesign thank you very much for your feedback.

but I think there is still a little misunderstanding.

My Goal: Having a data array (e.g. from a table row) and hydrate this array into my object. When extracting this same object, I want to have the same data array as my previous data array (e.g. to put it back into the table).

Prefix: Code Convention in this case is based on java and just an example [see example](http://geosoft.no/development/javastyle.html#Specific)

```php
class MyClass 
{
    protected $active = true;

    protected $name = '';

    public function isActive() : bool
    {
        return $this->active;
    }

    public function setActive(bool $active)
    {
        $this->active = $active;
    }

    public function getName() : string
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }
}
```

> Because there is no setter with name like `setIsActive`.

This is correct and based on convention, setting the Boolean var is done with `setActive`. This leads me directly to the different behavior from `get` vs. `is|has`. If the Setter should be `setIsActive` why shouldn't it be `setGetName` then? The `get` is a part of the getter prefix, and same is the `is` (thats what the filters are for, I thought).

When extracting this object with the ClassMethods Hydrator, I get an array of data which is not possible to use as data array for hydrating anymore. Except, I create a setter method, which do not follow the naming convention like the setters for "usual" getters.

Input Array:
```php
$data = [
    'name' => 'some content',
    'active' => true,
];
```
and this is what I got when using extract:
```php
[
    'name' => 'some content',
    'is_active' => true,
]
```

I think the difference is made in the extract method in [ClassMethods.php](https://github.com/zendframework/zend-hydrator/blob/master/src/ClassMethods.php#L159) in Line 159ff.

When I change this to
```php
                if (strpos($method, 'get') === 0) { // Line 159ff
                    $attribute = substr($method, 3);
                    if (!property_exists($object, $attribute)) {
                        $attribute = lcfirst($attribute);
                    }
                } elseif (strpos($method, 'is') === 0) { // this is added to correctly return array keys
                    $attribute = substr($method, 2);
                    if (!property_exists($object, $attribute)) {
                        $attribute = lcfirst($attribute);
                    }
                } elseif (strpos($method, 'has') === 0) { // this is added to correctly return array keys
                    $attribute = substr($method, 3);
                    if (!property_exists($object, $attribute)) {
                        $attribute = lcfirst($attribute);
                    }
                }
```

it works as expected.

> If you do not want the is_active on extraction, then remove the filter from the hydrator

If I do this, then I'll have not output for `(is_)active` at all. Therefore, this is no solution.

Maybe you can find some time read all this and lead me to the point where I'm getting it wrong.

Thanks in advance!

**Comment by froschdesign** [comment]
@skors 
> but I think there is still a little misunderstanding.

I am sorry, but your first post wasn't clear enough. Therefore I only answered to your wrong assumption:

> ```php
> var_dump($hydrator->hydrate(['is_active' => false], new MyClass()));
> // expected  { protected $active => bool(false) }

---

> …it works as expected.

Do not forget: it is only your expectations! The current implementation doesn't respect any Java code convention.
In the current version of `zend-hydrator` you must add a getter method or naming strategy to get the expected array result. Example:

```php
$mapNamingStrategy = new \Zend\Hydrator\NamingStrategy\MapNamingStrategy(
    [],
    [
        'isActive' => 'active',
    ]
);
$compositeNamingStrategy    = new \Zend\Hydrator\NamingStrategy\CompositeNamingStrategy(
    [
        'isActive' => $mapNamingStrategy,
    ],
    new \Zend\Hydrator\NamingStrategy\UnderscoreNamingStrategy()
);

$hydrator = new \Zend\Hydrator\ClassMethods();
$hydrator->setNamingStrategy($compositeNamingStrategy);
```
(Not tested, but it should work like this.)

But don't get me wrong: I like your suggestion. (Btw. it is a BC break)

**Comment by koseduhemak** [comment]
Using zendframework/zendframework: 2.5.3.

I would like to discuss this again, because many other modules (including f.e. doctrine are using isBool() as getter method and I would like to be consistent. This would be important if you use doctrine entities, which are getting bound to the form, in combination with ClassMethods hydrator).

For reference my originally intended post:

Problem: A checkbox in my form class does not get checked if object is bound to form. More specific: The hydrator ClassMethods does extract a wrong array key if I use `isBool()` instead of `getBool()` method as getter-method of my boolean property in my bound class object.

## Example:
Debugging output of breakpoint at `Zend\Form\Form.php`, method `bind`, line 305, inspecting variable `$data` (one line after the extract method gets called on the set ClassMethods Hydrator):
```
Array
(
    [categories] => 
    [countries] => 
    [dateStart] => DateTime Object
        (
            [date] => 2016-10-27 15:48:20.000000
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

    [dateEnd] => DateTime Object
        (
            [date] => 2017-10-27 15:48:20.000000
            [timezone_type] => 3
            [timezone] => Europe/Berlin
        )

    [created] => 
    [priceFrom] => 
    [priceUntil] => 5000
    [isPrice] => 1
)

```

As you can see the array key `isPrice` was extracted instead of the desired array key `price`. Therefore the checkbox element in my form does not getting checked. If I use a normal getter method f.e. `getPrice` instead of ìsPrice` everything works as expected (resulting array key is `price` and checkbox does get checked). 

I think it is good practice to use `isBool()` methods for better code readability (and of course, other packages like doctrine f. e. can work with `isBool()` methods to as getter methods).

I am not sure if this is desired behavior (then I would propose an improvement) or if it is not desired (then I think it is a bug). Any help, thoughts, hints are welcome.

koseduhemak

**Comment by skors** [comment]
if wanted, i can contribute a PR with tests for this

**Comment by weierophinney** [comment]
The behavior _is_ documented: `has`, `get`, and `is` prefixes are all stripped when using the `ClassMethods` hydrator. If those are important, then we have naming strategies for mapping the unprefixed names to prefixed versions (and vice versa). While the expectations you have may not match what we deliver, any such change would be a BC break; since you can achieve the same functionality by using other features of the library, it's not one we will consider.
