### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-hydrator#5]
This is a proposal I've made long time ago, and move it as a separate repository until this one would be created: https://github.com/zf-fr/hydrator

Some things should likely be changed, but from my memories the new hydrator was more flexible, much more efficient.

If someone would like to take it and submit a PR here. Maybe the awesome @weierophinney ?

**Comment by sandrokeil** [comment]
The description looks really interesting. :+1: for performance boost and benchmarks. This should be moved to this repo.

**Comment by vaclavvanik** [comment]
+1 for @bakura10 hydrator

**Comment by weierophinney** [comment]
I'm swamped currently; if somebody would be willing to create a PR with the changes proposed by @bakura10 , that would be fantastic. What I will evaluate is:

- Preservation of backwards compatibility and/or documented, clear migration path. These are crucial!
- Demonstrated improvement. Likely this will require two pull requests, one against current master with benchmarks (see the event manager and service manager repositories for examples using the athletic library), and the pull request with the updates proposed by @bakura10 , so we can compare objectively.
- Documentation. New features and capabilities are great. But if there's no documentation, how will developers know how to use them?

With those guidelines: any takers?

**Comment by bakura10** [comment]
Thank you @weierophinney , I definitely do'nt have time for doing that and on our current project we are using manual hydration so there is no reason for me to invest more time currently on that, but I'll be happy to review if anyone take my PR or have any questions on the chnages I've done.

**Comment by sandrokeil** [comment]
@weierophinney I add the benchmarks to master and develop branch. I use the benchmarks from @bakura10 [repo](https://github.com/zf-fr/hydrator) and update the classes to work with phpbench.

**Comment by robob4him** [comment]
No aggregate/event-based hydrator?

**Comment by weierophinney** [comment]
@robob4him 

> No aggregate/event-based hydrator?

We've had the `AggregateHydrator`, which is event-driven, for quite some time; perhaps you missed it?

**Comment by froschdesign** [comment]
@weierophinney 
I think he means the proposal from @bakura10, because there is no aggregate/event-based hydrator included.

**Comment by weierophinney** [comment]
I've been doing iterative improvements to the develop branch in preparation for a 3.0.0 release. The main changes:

- Usage of scalar typehints for parameters and return values, object typehints for parameters, and nullable typehints where appropriate. This includes formalizing passing context data/objects to strategies and naming strategies; with nullable types, scalar types, and object types, we can do this properly instead of by convention.
- Moving the various `*EnabledInterface` definitions to the appropriate subnamespaces.
- Standalone plugin manager, for use when zend-servicemanager is not available or desired.
- Renaming hydrators to include the `Hydrator` suffix (though we will keep the originals around as extensions of the new classes, each marked deprecated).
- More documentation (though there's still more to be done, and @froschdesign has indicated he's working on it).

From what I can see, the bulk of the performance optimizations were around the hydration and extraction context, which revolved around creating a reference to an object containing the object and data being hydrated, and the object from which extraction was occurring. The changes I made to the interfaces essentially nullify the need for that approach.

As such, I'm closing this one, as we're close to completing the changes for v3. We can do additional iterative improvements afterwards.
